[package]
name = "pe"
version = "0.1.0"
edition = "2018"

[dependencies]
csv = "1.1.6"
itertools = "0.10.1"
num = "0.4.0"
rayon = "1.5.1"
reikna = "0.12.3"
serde = { version = "1.0", features = ["derive"] }
